config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :holidays
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index", as:'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :holidays
    validates :name, length: {minimum:5, maximum:35}
    validates :email, length: {minimum:12, maximum:35}
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  belongs_to :employee
  #validates :name, length: {minimum:5, maximum:35}
  validates_presence_of :startdate, :enddate
  validate :end_date_is_after_start_date

  def end_date_is_after_start_date
    return if enddate.blank? || startdate.blank?
  
    if enddate < startdate
      errors.add(:enddate, "must be before the Start Date") 
    end 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
      module Users
      class SessionsController < Devise::SessionsController
        def destroy
          super do
            # Turbo requires redirects be :see_other (303); so override Devise default (302)
            return redirect_to after_sign_out_path_for(resource_name), status: :see_other
          end
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
    @curr_employee = Employee.find(params[:id]);
    @employee_holidays = Holiday.where(["employee_id = ?", @curr_employee])
   # @employee_assignned_name = Employee.find(@employee_assigned_id).name;
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :email)
    end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: %i[ show edit update destroy ]

  # GET /holidays or /holidays.json
  def index
    @holidays = Holiday.all
    #@curr_holiday = Holiday.find(params[:id]);
    # @curr_holiday = Holiday.find(1);
    # @employee_assigned_id = @curr_holiday.employee_id;
    # @employee_assignned_name = Employee.find(@employee_assigned_id).name;
  end

  # GET /holidays/1 or /holidays/1.json
  def show
    #@employeeAssigned = Holiday.find(holiday_params)
    #@employee = Employee.find(params[:id])
    @curr_holiday = Holiday.find(params[:id]);
    @employee_assigned_id = @curr_holiday.employee_id;
    @employee_assignned_name = Employee.find(@employee_assigned_id).name;
  end

  # GET /holidays/new
  def new
    @employees = Employee.all
    #@holiday = @employee.new
   # @employee = Employee.find(1)
    @holiday = Holiday.new
  end

  # GET /holidays/1/edit
  def edit
    @employee = Employee.find(params[:id])
    @holiday = @employee.holidays.build
     # @url_param = ['id'];
  end

  # POST /holidays or /holidays.json
  def create
    @holiday = Holiday.new(holiday_params)

    respond_to do |format|
      if @holiday.save
        format.html { redirect_to holiday_url(@holiday), notice: "Holiday was successfully created." }
        format.json { render :show, status: :created, location: @holiday }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holidays/1 or /holidays/1.json
  def update
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to holiday_url(@holiday), notice: "Holiday was successfully updated." }
        format.json { render :show, status: :ok, location: @holiday }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1 or /holidays/1.json
  def destroy
    @holiday.destroy

    respond_to do |format|
      format.html { redirect_to holidays_url, notice: "Holiday was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holiday
      @holiday = Holiday.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def holiday_params
      params.require(:holiday).permit(:startdate, :enddate, :employee_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @title = "Welcome to Holiday Booker"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper

    def get_employee_name_by_id(id)
        @curr_holiday = Holiday.find(id);
        @employee_assigned_id = @curr_holiday.employee_id;
        @employee_assignned_name = Employee.find(@employee_assigned_id).name;
        @employee_assignned_name
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Name:</strong>
    <%= employee.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ol>
        <% employee.errors.each do |error| %>
          <li class="alert alert-danger"><%= error.full_message %></li>
        <% end %>
      </ol>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, { :class => 'form-control'} %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, { :class => 'form-control'} %>
  </div>

  <div>
    <%= form.submit({:class => "btn btn-primary"}) %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to ALL employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div id="employees" class="col-lg-12 row">
  <% @employees.each do |employee| %>
    <div class="well well-lg col-lg-3">
      <%= render employee %>
      <p class="employeeIndexBtns">
        <%= link_to "Show this employee", employee, class:"btn btn-info" %>
        <%= link_to "New holiday for: #{employee.name}", :controller => holidays_path, :action => :new, :id =>employee.id, class:"btn btn-info" %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path, class:"btn btn-success" %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee), class:"btn btn-info" %> |
  <%= link_to "Back to employees", employees_path, class:"btn btn-info" %>
<div class="displayInline">
  <%= button_to "Destroy this employee", @employee, method: :delete, class:"btn btn-danger" %>
</div>
</div>
<hr/>
<div class="row">
<h1 class="displayInline col-lg-6"><%= "#{@employee.name.upcase}'s Holidays" %></h1>
<h5 class="displayInline col-lg-4"> <%= link_to "Add Holiday", :controller => holidays_path, :action => :new, :id =>@employee.id, class:"btn btn-info" %></h5></div>
<div id="holidays" class="col-lg-12 row displayInline row">
  <% @employee_holidays.each do |em| %>
   <div class="well well-lg col-lg-4 displayInlineBlock holidaysDiv">
  <p>
    <strong>Startdate:</strong>
    <%= em.startdate %>
  </p>

  <p>
    <strong>Enddate:</strong>
    <%= em.enddate %>
  </p>
  <p>
      <%= link_to "VIEW", holiday_path, class:"btn btn-info" %>
      <%= link_to "EDIT", edit_holiday_path, class:"btn btn-info" %>
    </p>
</div>
</div>
  <% end %>
</div>

app/views/holidays/_form.html.erb
<%= form_with(model: holiday, :html => {:id => 'holiday_form'}) do |form| %>
    <%  if holiday.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>
        <ul>
          <% holiday.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :startdate, style: "display: block" %>
      <%= form.date_field :startdate %>
    </div>

    <div>
      <%= form.label :enddate, style: "display: block" %>
      <%= form.date_field :enddate %>
    </div>

    <div>
      <%= form.label :employee_id, style: "display: block" %>
      <%= form.text_field :employee_id, class: 'employee_id_on_holiday_form' %>
      
      <%= collection_select(@employees, :name, 
      Employee.all, :id, :name, prompt: true) %>
      
      <%# Adds employees name if the form is used for editing (true = editing) %>
      <%# if !(defined?(@holiday)).nil? %>
      <%# was using this before adding in the select dropdown %>
      <%# if @holiday.employee_id %>
        (<%# "#{get_employee_name_by_id(holiday.employee_id)} [#{holiday.employee_id}] "%>)
      <%# end %>
      
  
      
    </div>
    <div>
      <%= form.submit %>
    </div>
<% end %>

<%= javascript_include_tag "form_listeners" %>

app/views/holidays/_holiday.html.erb
<div id="<%= dom_id holiday %>" class="well well-lg col-lg-3">
<% @duration = ((holiday.startdate.jd..holiday.enddate.jd).count) -1 %>
<h6><%= "DURATION: #{@duration} ( Days off)" %></h6>
<hr />
  <p>
    <strong>Startdate:</strong>
    <%= holiday.startdate %>
  </p>

  <p>
    <strong>Enddate:</strong>
    <%= holiday.enddate %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= holiday.employee_id %> (<%= @employee_assignned_name %>)
  </p>

</div>

app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>
 (<%= link_to "Back to Employee", employee_path %>)

<%= render "form", holiday: @holiday %>

<br>

<div>
  <%= link_to "Show this holiday", @holiday %> |
  <%= link_to "Go to ALL holidays", holidays_path %>
  <%= link_to "Back to Employee (#{@employee_assignned_name}) ", employee_path %>
</div>

app/views/holidays/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Holidays</h1>

<div id="holidays" class="col-lg-12 row">
  <% @holidays.each do |holiday| %>
    <div class="well well-lg col-lg-4">
    <div id="<%= dom_id holiday %>">
  <p>
    <strong>Startdate:</strong>
    <%= holiday.startdate %>
  </p>

  <p>
    <strong>Enddate:</strong>
    <%= holiday.enddate %>
  </p>

  <p>
    <strong>Employee:</strong>
    <%= holiday.employee_id %> (<%= get_employee_name_by_id(holiday.employee_id) %>)
  </p>

</div>
    <p>
      <%= link_to "Show this holiday", holiday, class:"btn btn-info" %>
    </p>
    </div>
  <% end %>
</div>

<%= link_to "New holiday", new_holiday_path, class:"btn btn-info" %>

app/views/holidays/new.html.erb
<h1>New holiday</h1>

<%= render "form", holiday: @holiday %>

<br>

<div>
  <%= link_to "Back to holidays", holidays_path %>
</div>

app/views/holidays/show.html.erb
<p style="color: green"><%= notice %></p>
<% @link_text = "Back to Employee:" + @employee_assignned_name.upcase%>
<%= link_to @link_text, employee_path %>

<%=  @employeeAssigned %>

<%= render @holiday %>
<div>
  <%= link_to "Edit this holiday", edit_holiday_path(@holiday) %> |
  <%= link_to "Back to holidays", holidays_path %>

  <%= button_to "Destroy this holiday", @holiday, method: :delete, class:"btn btn-danger" %>
</div>

app/views/home/index.html.erb
<h1><%= @title %></h1>

<% if user_signed_in? %>
   <h2>Hello <%= current_user.email %></h2>
   <h3>Your role: <%= current_user.role %></h3>
   <%= button_to("Log out", destroy_user_session_path, data: { turbo: false, turbo_method: :delete }, method: :delete) %>
<% else %>
   <h2> You are not signed in </h2>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
   <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-decoration-none homeBtn">
        Home
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%# link_to "Home", home_path, class:"nav-link px-2 text-secondary" %></li>
          <li><%= link_to "New Employee", new_employee_path, class:"nav-link px-2 text-white" %></li>
          <li><%= link_to "All Employees", employees_path, class:"nav-link px-2 text-white" %></li>
          <li><%= link_to "All Holidays", holidays_path, class:"nav-link px-2 text-white" %></li>
          <li><%= link_to "New holiday", new_holiday_path, class:"nav-link px-2 text-white" %></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-white bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
        <% if !user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path, class:"btn btn-warning" %>
        <%= link_to "Sign in", new_user_session_path, class:"btn btn-outline-light me-2" %>
        <% else %>
           <%= button_to("Log out", destroy_user_session_path, data: { turbo: false, turbo_method: :delete }, method: :delete, class:'btn btn-outline-light me-2') %>
        <% end %>
        </div>
      </div>
    </div>
  </header>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>